import BlackTick from '../../../public/images/check-black.svg';
import InfiniteBlue from '../../../public/images/infinite-blue.svg';
import InfinitePurple from '../../../public/images/infinte-purple.svg';
import DarkBlueTick from '../../../public/images/tick-dark-blue.svg';
import LightBlueTick from '../../../public/images/tick-lightBlue.svg';
import PurpleTick from '../../../public/images/tick-purple.svg';

export interface TableFeaturesSchema {
  mainText: string;
  standard: string;
  pro: string;
  team: string;
  enterprise: string;
}

export interface AdvanceFeaturesSchema {
  heading: string;
  tableData: TableFeaturesSchema[];
}

export const AdvanceFeaturesData: AdvanceFeaturesSchema = {
  heading: 'Top-Level Features',
  tableData: [
    {
      mainText: 'Unique Linq pages',
      standard: '1',
      pro: '5',
      team: InfiniteBlue,
      enterprise: InfinitePurple,
    },
    {
      mainText: 'Free mobile app for product management',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Free mobile app for product management',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'In-house printing and fulfillment',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Best-in-class content customization',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Contact collection and management',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Enterprise level security',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Real-time analytics',
      standard: 'Basic',
      pro: 'Advanced',
      team: 'Teams',
      enterprise: 'Teams',
    },
    {
      mainText: 'Business card scanner',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Customize lead capture and follow-up',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'CRM and marketing integrations',
      standard: '',
      pro: '5',
      team: '300+',
      enterprise: '6000+',
    },
    {
      mainText: 'Admin management tools & dashboard',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Bulk actions and templates',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Automate contact management and follow-ups',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Directory Sync and Single Sign On',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
    {
      mainText: 'Priority design and integration support',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
    {
      mainText: 'Linq product discount',
      standard: '',
      pro: '15% off',
      team: '50% off',
      enterprise: 'FREE',
    },
  ],
};
export const BrandedExperienceData: AdvanceFeaturesSchema = {
  heading: 'Fully-Branded Experience',
  tableData: [
    {
      mainText: 'Remove Linq branding',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Add business logo',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Shared asset library',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Standardized content and messaging templates',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Customized employee permission controls',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Expert custom design assistance',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
    {
      mainText: 'Custom branded QR code',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
  ],
};
export const CustomizedPageData: AdvanceFeaturesSchema = {
  heading: 'Customize Page Content',
  tableData: [
    {
      mainText: 'Unlimited content editing (stay up to date)',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Customizable bio and contact info',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Social media profile icons',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Quick contact icons',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Photo gallery',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Unlimited customizable links',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Expandable text boxes',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Collect reviews',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Video embedding (YouTube, Vimeo)',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Audio embedding (Spotify, Soundcloud)',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Collect payments with embeddable storefront',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Calendar scheduling (Calendly, Acuity)',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Downloadable PDFs or files)',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Customizable forms',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Typeform integration (surveys)',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Team directory',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Customized employee permission controls',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
  ],
};
export const SharedLinqData: AdvanceFeaturesSchema = {
  heading: 'Fully-Branded Experience',
  tableData: [
    {
      mainText: 'Unlimited page sharing',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Send email from Linq app',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Send SMS from Linq app',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Downloadable QR code',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Save to digital wallet',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Custom virtual background',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Custom email signature',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'iOS widgets (lockscreen & homescreen)',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Link-in-bio capability',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Redirect page to any URL',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
  ],
};
export const CapturedContactData: AdvanceFeaturesSchema = {
  heading: 'Capture Contacts',
  tableData: [
    {
      mainText: 'Customizable contact exchange',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Manual contact creation',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Customizable lead capture form',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Business card scanner',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
  ],
};
export const ManagedContactsData: AdvanceFeaturesSchema = {
  heading: 'Manage Contacts',
  tableData: [
    {
      mainText: 'Label and group contacts',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Add contact notes',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Create follow-up reminders',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Download contact cards',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Bulk export contacts',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Auto-sync contacts to CRM',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Share contacts with your team',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Automate contact management with workflows',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
  ],
};
export const NurtureContactsData: AdvanceFeaturesSchema = {
  heading: 'Nurture Contacts',
  tableData: [
    {
      mainText: 'Automated follow-up messages',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Custom follow-up messages',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Customizable follow-up templates',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
  ],
};
export const CRMIntegrationsData: AdvanceFeaturesSchema = {
  heading: 'CRM Integrations',
  tableData: [
    {
      mainText: 'Salesforce',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Hubspot',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Microsoft',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Zoho',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Google Contacts',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Custom field mapping',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: '35+ email marketing integrations',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: '300+ industry-specific CRMs',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: '5,000+ integrations with Zapier',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Dedicated integration specialist',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
  ],
};
export const AnalyticsData: AdvanceFeaturesSchema = {
  heading: 'Analytics',
  tableData: [
    {
      mainText: 'Real-time analytics',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Click-level analytics',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Event stream',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Team-wide analytics',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Data export',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
  ],
};
export const SecurityData: AdvanceFeaturesSchema = {
  heading: 'Analytics',
  tableData: [
    {
      mainText: 'Data encryption',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'PCI Level 1 compliant',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Customer privacy protection',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'SOC 2 Report',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
  ],
};
export const AdminManagementData: AdvanceFeaturesSchema = {
  heading: 'Admin Management',
  tableData: [
    {
      mainText: 'Unlimited page templates',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Bulk content editing',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Bulk employee upload',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Bulk product activation',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Remote product reassignment',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Subteams & employee grouping',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Shared asset library',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Customized employee permission controls',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
  ],
};
export const CustomerServiceData: AdvanceFeaturesSchema = {
  heading: 'Customer Service',
  tableData: [
    {
      mainText: 'In-house printing and fulfillment',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Live chat support',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Email support',
      standard: BlackTick,
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Weekly virtual training sessions',
      standard: '',
      pro: LightBlueTick,
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Customized onboarding plan',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Live onboarding for team admins',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Dedicated teams success manager',
      standard: '',
      pro: '',
      team: DarkBlueTick,
      enterprise: PurpleTick,
    },
    {
      mainText: 'Priority Zoom and email support',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
    {
      mainText: 'Dedicated integration specialist',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
  ],
};
export const DirectorySyncData: AdvanceFeaturesSchema = {
  heading: 'Directory Sync (HRIS)',
  tableData: [
    {
      mainText: 'Auto add and remove team members',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
    {
      mainText: 'Custom attribute mapping',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
    {
      mainText: 'Sync with any SCIM v2.0 provider',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
    {
      mainText: 'Azure Active ',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
    {
      mainText: 'DirectoryGoogle Directory',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
    {
      mainText: 'Okta',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
    {
      mainText: 'Rippling',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
    {
      mainText: 'Workday',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
    {
      mainText: 'Bamboo HR',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
    {
      mainText: 'Breathe HR',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
  ],
};
export const SingleSignOnData: AdvanceFeaturesSchema = {
  heading: 'Directory Sync (HRIS)',
  tableData: [
    {
      mainText: 'Connect with any SAML 2.0 provider',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
    {
      mainText: 'Connect with any OpenID Connect provider',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
    {
      mainText: 'Microsoft / Azure',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
    {
      mainText: 'Google',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
    {
      mainText: 'Okta',
      standard: '',
      pro: '',
      team: '',
      enterprise: PurpleTick,
    },
  ],
};
